### ISSUE TITLE
Error message 'undefined is not a function (near '...e.result._hits?.map...')'

### ISSUE THREAD

**Issue by kintopp** [knaw-huc/textannoviz#83]
Just ran this search https://transcriptions.globalise.huygens.knaw.nl/?frag=Scan&from=0&size=10&sortBy=_score&sortOrder=desc&query=eyJkYXRlRnJvbSI6IjE1MDAtMDEtMDEiLCJkYXRlVG8iOiIxODAwLTAxLTAxIiwiZnVsbFRleHQiOiJNaWNoaWVsIFNsb25zIHZhbiBHcmF1d3dpbmNrZWwiLCJ0ZXJtcyI6e319 and got this error message:

Oops!
Sorry, an unexpected error has occurred.
undefined is not a function (near '...e.result._hits?.map...')

The search was for 'Michiel Slons van Grauwwinckel' (no quotes)

Reloaded the page in the browser, and it worked as expected. 
OSX 14.3, Safari 17.3

**Comment by svandaalen** [comment]
Thanks for the bug report! We updated TAV yesterday for it to work with the new version of Broccoli that enables the logging of search queries. This new Broccoli version included an upgrade to a new version of ES, so that needed some patching in TAV. The error that you are describing is related to this new version of ES. It might be that the previous version of TAV was cached by the browser and that's why you received this error. This is the most likely cause, especially because a page reload resolved the issue. This page reload will have fetched the new version of TAV from the server.

Let me know if this happens more frequently :).

**Comment by kintopp** [comment]
Thanks, Sebastiaan. We've had only one external query about this, and that was also resolved as above by reloading the page, so I think it's safe to close this issue.
